---
- name: Add Cilium Helm repository
  shell: |
    helm repo add cilium https://helm.cilium.io
    helm repo update
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install Cilium
  shell: |
    helm upgrade --install cilium cilium/cilium \
      --namespace kube-system \
      --create-namespace \
      --version 1.18.1 \
      --set kubeProxyReplacement=false \
      --set operator.replicas=1 \
      --wait
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for Cilium DaemonSet
  shell: |
    kubectl rollout status daemonset/cilium \
      -n kube-system \
      --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for Cilium Operator
  shell: |
    kubectl rollout status deployment/cilium-operator \
      -n kube-system \
      --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Verify Cilium
  shell: |
    kubectl get pods -n kube-system -l app.kubernetes.io/part-of=cilium
  register: cilium_status
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- debug:
    var: cilium_status.stdout_lines