---
# ---------------------------------------------------------
# Add Cilium Helm Repository
# ---------------------------------------------------------

- name: Add Cilium Helm repository
  shell: |
    helm repo add cilium https://helm.cilium.io
    helm repo update
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# ---------------------------------------------------------
# Install Cilium
# ---------------------------------------------------------

- name: Install Cilium
  shell: |
    helm upgrade --install cilium cilium/cilium \
      --namespace kube-system \
      --create-namespace \
      --version 1.18.1 \
      --set kubeProxyReplacement=false \
      --set operator.replicas=1
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# ---------------------------------------------------------
# Verify Helm Release
# ---------------------------------------------------------

- name: Verify Cilium Helm release
  shell: |
    helm list -n kube-system | grep cilium
  register: cilium_helm
  changed_when: false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- debug:
    var: cilium_helm.stdout_lines