---
- name: Configure all Kubernetes nodes
  hosts: controlplane:dataplane
  become: true
  roles:
    - common

- name: Configure Kubernetes control plane
  hosts: controlplane
  become: true
  roles:
    - controlplane

- name: Install CNI
  hosts: controlplane
  become: true
  roles:
    - cni